version: 0.2

phases:
  install:
    commands:
      - echo Installing cfn-lint
      - pip install cfn-lint
  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase...
  build:
    commands:
      - echo Build started on `date`
#      - mvn install
      - for filename in templates/*; do echo $filename; cfn-lint -i W --template $filename; done
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
